/**
 * A set of events for Mind Flayer.
 */

export const MindFlayerEvents = {
    
    MIND_FLAYER_FIRE_FIREBALL: "MIND_FLAYER_FIREBALL",
    MIND_FLAYER_FIREBALL_HIT_WALL: "MIND_FLAYER_FIREBALL_HIT_WALL",
    MIND_FLAYER_FIREBALL_HIT_PLAYER: "MIND_FLAYER_FIREBALL_HIT_PLAYER",
    MIND_FLAYER_TELEPORT: "MIND_FLAYER_TELEPORT"
}