/**
 * A set of events for Mind Flayer.
 */

export const MindFlayerEvents = {
    
    MIND_FLAYER_FIRE_FIREBALL: "MIND_FLAYER_FIRE_FIREBALL",
    MIND_FLAYER_SUMMON_SHADOW_DEMON: "MIND_FLAYER_SUMMON_SHADOW_DEMON",
    MIND_FLAYER_TELEPORT: "MIND_FLAYER_TELEPORT",
    MIND_FLAYER_DEAD: "MIND_FLAYER_DEAD"
}