/**
 * A set of events for Mind Flayer.
 */

export const MindFlayerEvents = {
    
    MIND_FLAYER_FIRE_FIREBALL: "MIND_FLAYER_FIRE_FIREBALL",
    MIND_FLAYER_SPAWN_DEMON_CIRCLE: "MIND_FLAYER_SPAWN_DEMON_CIRCLE",
    MIND_FLAYER_TELEPORT: "MIND_FLAYER_TELEPORT",
    MIND_FLAYER_DEAD: "MIND_FLAYER_DEAD"
}