/**
 * A set of events for Shadow Demon.
 */

export const ShadowDemonEvents = {
    SHADOW_DEMON_FIRE_FIREBALL: "SHADOW_DEMON_FIRE_FIREBALL",
    FIREBALL_HIT_SHADOW_DEMON: "FIREBALL_HIT_SHADOW_DEMON",
    SHADOW_DEMON_SWIPE: "SHADOW_DEMON_SWIPE"
}