export const DemonKingEvents = {
    
    STRUCK_LIGHTNING: "STRUCK_LIGHTNING",

    LIGHTNING_STRIKE_ENDED: "LIGHTNING_STRIKE_ENDED",

    SPAWN_DEATH_CIRCLE: "SPAWN_DEATH_CIRCLE",

    SKULLS_SPAWN: "SKULLS_SPAWN",

    SKULL_DESPAWNED: "SKULL_DESPAWNED",

    SKULLS_EXPANDED: "SKULLS_EXPANDED",

    SWIPED: "SWIPED",
    
    SWIPE_HIT_PLAYER: "SWIPE_HIT_PLAYER"
}