export const DemonKingEvents = {
    
    STRUCK_LIGHTNING: "STRUCK_LIGHTNING",

    LIGHTNING_STRIKE_ENDED: "LIGHTNING_STRIKE_ENDED",

    SPAWN_DEATH_CIRCLE: "SPAWN_DEATH_CIRCLE",

    SKULLS_SPAWN: "SKULLS_SPAWN",

    SKULLS_EXPANDED: "SKULLS_EXPANDED"
    
}